---
name: Update catalogues
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:
  push:
jobs:
  update:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        catalogue:
          # - version: v5
          #   ref: f466c4c16e7d9f1f17d3b3f17e254e7d6cfa1d0f
          - version: current
      max-parallel: 1
    steps:
      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
      - name: Check-out the data branch
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          ref: data
          persist-credentials: true
      - name: Check-out the main repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          repository: layday/instawow
          ref: ${{ matrix.catalogue.ref }}
          path: instawow
          persist-credentials: false
      - name: Install instawow
        run: uv tool install -p 3.13 ./instawow
      - name: Generate ${{ matrix.catalogue.version }} catalogue
        run: instawow generate-catalogue --start-date 2025-07-21
        env:
          INSTAWOW_ACCESS_TOKENS: ${{ secrets.INSTAWOW_ACCESS_TOKENS }}
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7.1.0
        with:
          commit_message: Update ${{ matrix.catalogue.version }} catalogue
          branch: data
          file_pattern: base-catalogue-v*.json
